site_name: mooGP documentation
theme:
  name: mkdocs
  logo: https://github.com/evancbarnett/mooGP/blob/main/logo/moogp_logo_core.svg
repo_url: https://github.com/evancbarnett/moogp/
docs_dir: examples
nav:
  - Getting Started: 00_getting_started.ipynb
  - Example Usage:
    - Trend: 01_trend_specification.ipynb
  - README: index.md
plugins:
  - mkdocs-jupyter
  - include-markdown
  - search